### PR TITLE
Minor codestyle

### PR DESCRIPTION
**Pull request by sabieber**

### CODE REVIEW

**Comment by kotcity** [comment]
Wow! I'm so happy to have a contributor already. Really solid work! If you want to contribute more "design" work and less "clean up my crummy code", I can have a conversation with you on what I'm thinking for the simulator / engine. Let me know and thanks again :)

**Comment by sabieber** [comment]
Yeah I would like to contribute more on the design side of the project for sure.
These two pull requests were just the result of me getting a bit of an overview of the project structure.

**Comment by kotcity** [comment]
cool... give me a little bit to write up some of my thoughts and we can either correspond or hop on some chat program.

**Comment by sabieber** [comment]
Sounds good 👍

**Comment by kotcity** [comment]
Added braindump / roadmap... https://github.com/kotcity/kotcity/blob/master/docs/KotCity.png do you have any areas of interest here? For instance, if you were to work on pathfinder / transit options I can pursue land values / desirability.

**Comment by sabieber** [comment]
Thanks for writing the very detailed roadmap. I had a first look at it but am not sure what areas I should work on first as I never built a city simulator or anything similar before 😅 If thats okay with you I would first like to work on some minor stuff (cleaning up the UI, better map rendering, ...) and in parallel have a more detailed at the concepts and classes that are already there.

Do you have a messenger in mind where we could communicate a little bit better on these topics? For example Slack or Gitter or something similar.

**Comment by kotcity** [comment]
>  as I never built a city simulator or anything similar before

Don't worry, me neither :)

>  If thats okay with you I would first like to work on some minor stuff (cleaning up the UI, better map rendering, ...) and in parallel have a more detailed at the concepts and classes that are already there.

Totally... my UI is not very elegant.

> Do you have a messenger in mind where we could communicate a little bit better on these topics? For example Slack or Gitter or something similar.

I just created a gitter channel: https://gitter.im/kotcity/Lobby
I'm in there already... we can chat more there! Thanks again!

**Pull request merged**
